version: "3.9"

services:
  db:
    image: mariadb:10.6
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      MYSQL_ROOT_PASSWORD: senha_root
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: senha_segura
    volumes:
      - /storage/pods_data/nextcloud/mysql:/var/lib/mysql
    networks:
      local_network:
        ipv4_address: <Your Ip of Choise> #Optional

  app:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      MYSQL_HOST: <Your Ip of Choise>
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: senha_segura
    volumes:
      - /storage/pods_data/nextcloud/html:/var/www/html
    networks:
      local_network:
        ipv4_address: <Your Ip of Choise> #Optional

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096" # Porta Web
    volumes:
      - /storage/pods_data/jellyfin/config:/config
      - /storage/jelly_media/media:/media # Conteúdo de mídia compartilhado
    environment:
      - TZ=America/Sao_Paulo
    networks:
      local_network:
        ipv4_address: <Your Ip of Choise> #Optional

  ftp:
    image: delfer/alpine-ftp-server
    container_name: ftp-server
    restart: unless-stopped
    ports:
      - "21:21"     # Porta FTP padrão
      - "21000-21010:21000-21010" # Portas para modo passivo
    environment:
      - USERS=admin|admin123|/media
      # - ADDRESS=0.0.0.0 # substitua pelo IP local
      - PASV_MIN_PORT=21000
      - PASV_MAX_PORT=21010
      - TZ=America/Sao_Paulo
    volumes:
      - /storage/jelly_media/media:/media # Mesma pasta do Jellyfin
    networks:
      local_network:
        ipv4_address: <Your Ip of Choise> #Optional

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=80
      - TORRENTING_PORT=6881
    volumes:
      - /storage/pods_data/qbittorrent/config:/config
      - /storage/jelly_media/media:/downloads #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      local_network:
        ipv4_address: <Your Ip of Choise> #Optional

networks:
  local_network:
    external: true
    name: local_net_macvlan